config/routes.rb
Caminar::Application.routes.draw do
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to=> "site#index"
  resources :site_comments, only: [:create, :destroy]

  # SITE CONTROLLER
  match '/new', to: "site#new", as: "email"
  match '/:event', to: "site#index", as: "index"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :name, :email, :text
end

app/models/home_photo.rb
class HomePhoto < ActiveRecord::Base
  
  attr_accessible :text, :position, :photo
  
  has_attached_file :photo,
    :styles => {
      :home => "959x430#",
      :small=> "150x150>"},
    :storage => :s3,
    :bucket => "caminar",
    :s3_options     => {
      :server => "s3-website-us-east-1.amazonaws.com"},
    :s3_credentials => "#{Rails.root}/config/s3.yml",
    :path => "/#{Rails.env}/home_photos/:attachment/:style/:id/:filename"

end

app/models/option.rb
class Option < ActiveRecord::Base
  attr_accessible :key, :value
  #Options se deberán crear desde el seeds.rb
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :title, :text, :contact_address, :meta_title, :meta_description, :key
  geocoded_by :contact_address
  before_validation :geocode
end

app/models/page_module.rb
class PageModule < ActiveRecord::Base
  attr_accessible :text, :title, :position
end

app/models/professional.rb
class Professional < ActiveRecord::Base
  attr_accessible :name, :title, :text, :position, :photo


  has_attached_file :photo,
    :styles => {
      :thumb=> "100x100#",
      :small=> "150x150#"},
    :storage => :s3,
    :bucket => "caminar",
    :s3_options => {
    :server => "s3-website-us-east-1.amazonaws.com"},
    :s3_credentials => "#{Rails.root}/config/s3.yml",
    :path => "/#{Rails.env}/professionals/:attachment/:style/:id/:filename"
end

app/models/site_comment.rb
class SiteComment < ActiveRecord::Base
  attr_accessible :name, :email, :text
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SimpleCaptcha::ControllerHelpers
  protect_from_forgery
  I18n.locale = 'es'

  def site_values 
    ActionMailer::Base.default_url_options[:host] = 'localhost:3000'
    @contact_page = Page.find_by_key("Contacto")
    telefono = Option.where(:key => "telefono").first
    @telefono = telefono.value if telefono
    footer = Option.where(:key => "footer").first
    @footer = footer.value if footer
    @meta_title = Page.find_by_key("Inicio").meta_title
    @meta_description = Page.find_by_key("Inicio").meta_description
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    
  end

  def create
    @comment = Comment.create(params[:comment])
    flash[:notice] = "Gracias por dejarnos tu comentario."
    redirect_to root_path(:event=>"comments")
  end

  def destroy
    
  end

end

app/controllers/site_comments_controller.rb
class SiteCommentsController < ApplicationController

  def create
    if simple_captcha_valid?
      @comment = SiteComment.create(params[:site_comment])
      flash[:notice] = "Gracias por dejarnos tu comentario."
      redirect_to root_path(:event=>"comments")
    else
      flash[:notice] = "El codigo captcha no es válido"
      redirect_to root_path(:event=>"comments")
    end
  end

  def destroy
    
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_filter :site_values

  def index
  	case params[:event]
      when "about"
        @event = "about"
        @page = Page.where(:key => "Quienes somos").first
      when "professionals"
        @event = "professionals"
        @page = Page.where(:key => "Profesionales").first
        @professionals = Professional.all
      when "contact"
        @event = "contact"
        @page = Page.where(:key => "Contacto").first
      when "comments"
        @event = "comments"
        @comment = SiteComment.new
        @comments = SiteComment.paginate :per_page => 6, :page => params[:page], :order=>"created_at DESC"
      else
        @event = "home"
        @home_photos = HomePhoto.all
        @page_modules = PageModule.all.reverse
    end 
  end

  def new
    Contact.new_contact(params).deliver
    flash[:notice] = "Gracias! Tu consulta fue enviada."
    @event = "contact"
    render "index"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def map
    if @contact_page
      image_tag "http://maps.google.com/maps/api/staticmap?center=#{@contact_page.contact_address}&zoom=14&size=256x256&maptype=roadmap&markers=color:red%7Ccolor:red%7Clabel:C%7C#{@contact_page.latitude.to_s},#{@contact_page.longitude}&sensor=false"
    end
  end

  def address
    raw(@contact_page.contact_address.gsub(",", "<br>")) if @contact_page && @contact_page.contact_address
  end

  def notice
    flash[:notice]
  end

end

app/helpers/site_comments_helper.rb
module SiteCommentsHelper
end

app/views/contact/new_contact.html.haml
= @content
%br
Para responder este mail, hace click aca 
= mail_to @email, @email

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Instituto Caminar Monte Grande

    
    %meta{:"http-equiv" => "Content-Type", :content => "text/html;charset=utf-8" } 
    %meta{:name => "description", :content => @meta_description.to_s + ".Centros de rehabilitación en zona sur. Información sobre centros de rehabilitación en zona sur. Centro médico en zona sur. Información de centro de rehabilitación zona sur. Teléfono de instituto caminar monte grande zona sur."}
    %meta{:name => "title", :content => @meta_title.to_s}
    %meta{:name => "url", :content => "http://www.institutocaminar.com.ar" }
    %meta{:name => "site_name", :content => "Instituto Caminar" }

    = stylesheet_link_tag    "application", :media => "all"
    = stylesheet_link_tag    "site"

    = javascript_include_tag "jquery"
    = javascript_include_tag "s3Slider"
    = javascript_include_tag "application"

    = csrf_meta_tags
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-34911047-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
  %body{:onload => ("initialize()")}
    .wrapped
      .main-container
        .header
          .top
            .slogan
              = image_tag("logo.png", :class=>"logo")
            .call-number
              = @telefono
          .menu
            .button.first
              = link_to raw("<span>Home</span>"), index_path("home"), :class => ("selected" if @event == "home") 
            .button
              = link_to raw("<span>¿Quiénes somos?</span>"), index_path("about"), :class => ("selected" if @event == "about") 
            .button
              = link_to raw("<span>Profesionales</span>"), index_path("professionals"), :class => ("selected" if @event == "professionals") 
            .button
              = link_to raw("<span>Comentarios</span>"), index_path("comments"), :class => ("selected" if @event == "comments") 
            .button.last
              = link_to raw("<span>Contacto</span>"), index_path("contact"), :class => ("selected" if @event == "contact") 
        = yield

app/views/site/_about.html.haml
.middle
  .professional-title
    ¿Quiénes Somos?
  .professional-text
    = raw @page.text 

app/views/site/_comments.html.haml
.middle
  - if notice
    %p.notice= notice
  .comment-title
    .left
      Dejanos tu comentario
    .right
      Últimos Comentarios
  .clear
  .comment-section
    .left
      = form_for @comment do |f|
        .fields
          .field
            = f.text_field :name, :placeholder=> "Name"
          .field
            = f.text_field :email, :placeholder=> "Email"
          .field
            = f.text_area :text
          .field
            = show_simple_captcha 
          .field.submit
            = f.submit "Comentar"
    .right
      .timeline
        - @comments.each do |comment|
          .comment
            %span{:class=>"name"}
              = comment.name
            %span{:class=>"date"}
              = comment.created_at.strftime("%d/%m/%Y - %H:%M %p")
            .text
              = comment.text
    .clear
      = will_paginate @comments, :next_label=>"Siguiente", :previous_label=>"Atrás"

app/views/site/_contact.html.haml
.middle
  .contact-title
    Contacto
    - if notice
      %br
      %span{:style => "color:red;"}
        = notice
  .contact
    - if @contact_page
      .left
        .address 
          = address
        %br
        .map  
          = map
      .right
        = form_tag email_path do
          .fields
            .field
              = text_field_tag :name, nil, :placeholder=> "Nombre"
            .field
              = text_field_tag :email, nil, :placeholder=> "Email"
            .field
              = text_area_tag :content
            .field.submit
              = submit_tag "Enviar"  

app/views/site/_footer.html.haml
.footer
  .links
    = raw @footer

app/views/site/_home.html.haml
.middle
  .home_photo
    #s3slider
      %ul{:id => "s3sliderContent"}
        - @home_photos.each do |hp|
          %li.s3sliderImage
            =image_tag(hp.photo.url(:home))
            %span
              = hp.text.html_safe
        .clear.s3sliderImage
-if @page_modules && @page_modules.size == 3
  .page_modules
    - @page_modules.each_with_index do |page_module, i|
      .module{:id => "module-#{i}"}
        .title
          = page_module.title
        .text
          = page_module.text.html_safe
    .clear

app/views/site/_professionals.html.haml
.middle
  .professional-title
    Profesionales
  .professional-text
    = raw @page.text
  .professionals
    - @professionals.each do |professional|
      .one-professional
        - if professional.photo.file?
          .left
            = image_tag professional.photo.url(:small)
        - if professional.photo.file?
          .right
            .content
              .name
                = professional.title
              .text
                = raw professional.text
        -else
          .content
            .name
              = professional.title
            .text
              = raw professional.text

app/views/site/index.html.haml
= render :partial => "/site/#{@event}.html.haml"
= render :partial => "/site/footer.html.haml"